# Generated by Django 5.2.16 on 2026-07-28 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0002_alter_medicaldocument_patient'),
        ('medications', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('or', 'Oriya')], default='hi', max_length=8)),
                ('original_text', models.TextField(blank=True, help_text='Original prescription text or medical phrase')),
                ('simplified_text', models.TextField(blank=True, help_text='Simplified plain-language medical guidance')),
                ('translated_text', models.TextField(blank=True, help_text='Text translated into regional language')),
                ('audio_file', models.FileField(blank=True, help_text='Generated voice guidance audio file', null=True, upload_to='translations/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='medical.medicaldocument')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
