# Generated by Django 5.2.16 on 2026-07-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='caregiver_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='dose_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('missed', 'Missed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='reminder',
            name='missed_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
