export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🌐' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳' },
];

export const UI_STRINGS: Record<string, Record<string, string>> = {
  en: {
    app_title: 'Swasthya AI',
    app_subtitle: 'Rural Healthcare Communication Assistant',
    greeting: 'Namaste',
    pillbox_title: '5-Day Visual Pillbox',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    night: 'Night',
    before_food: 'Before Food',
    after_food: 'After Food',
    with_food: 'With Food',
    mark_taken: 'Take Dose',
    dose_taken: 'Dose Taken ✅',
    streak: 'Day Adherence Streak',
    scan_prescription: 'Scan Prescription',
    health_card: 'ABHA Health Card',
    emergency_sos: 'EMERGENCY SOS',
    listen_voice: 'Listen in',
    view_all_prescriptions: 'My Prescriptions',
    asha_roster: 'Rural Patient Roster',
    sync_status: 'Sync Status: Online',
    sync_offline: 'Working Offline (Cached)',
    caregiver_monitoring: 'Family Adherence Monitor',
  },
  hi: {
    app_title: 'स्वास्थ्य एआई',
    app_subtitle: 'ग्रामीण स्वास्थ्य संचार सहायक',
    greeting: 'नमस्ते',
    pillbox_title: '5-दिवसीय विजुअल पिलबॉक्स',
    morning: 'सुबह',
    afternoon: 'दोपहर',
    evening: 'शाम',
    night: 'रात',
    before_food: 'खाने से पहले',
    after_food: 'खाने के बाद',
    with_food: 'खाने के साथ',
    mark_taken: 'दवा लें',
    dose_taken: 'दवा ले ली गई ✅',
    streak: 'दिनों का लगातार नियम',
    scan_prescription: 'पर्चा स्कैन करें',
    health_card: 'आभा स्वास्थ्य कार्ड',
    emergency_sos: 'आपातकालीन सहायता (SOS)',
    listen_voice: 'आवाज में सुनें',
    view_all_prescriptions: 'मेरे सभी पर्चे',
    asha_roster: 'ग्रामीण मरीज सूची',
    sync_status: 'सिंक स्थिति: ऑनलाइन',
    sync_offline: 'ऑफलाइन मोड (सुरक्षित)',
    caregiver_monitoring: 'परिवार दवा निगरानी',
  },
  mr: {
    app_title: 'स्वास्थ्य एआय',
    app_subtitle: 'ग्रामीण आरोग्य सहाय्यक',
    greeting: 'नमस्कार',
    pillbox_title: '५-दिवसीय व्हिज्युअल पिलबॉक्स',
    morning: 'सकाळ',
    afternoon: 'दुपार',
    evening: 'संध्याकाळ',
    night: 'रात्र',
    before_food: 'जेवणापूर्वी',
    after_food: 'जेवणानंतर',
    with_food: 'जेवणासोबत',
    mark_taken: 'औषध घ्या',
    dose_taken: 'औषध घेतले ✅',
    streak: 'दिवसांचे सातत्य',
    scan_prescription: 'प्रिस्क्रिप्शन स्कॅन करा',
    health_card: 'आभा आरोग्य कार्ड',
    emergency_sos: 'आपत्कालीन SOS',
    listen_voice: 'आवाजात ऐका',
    view_all_prescriptions: 'माझी औषधपत्रे',
    asha_roster: 'रुग्ण यादी',
    sync_status: 'सिंक स्थिती: ऑनलाइन',
    sync_offline: 'ऑफलाइन मोड',
    caregiver_monitoring: 'कुटुंब आरोग्य देखरेख',
  },
  ta: {
    app_title: 'சுவஸ்தியா AI',
    app_subtitle: 'கிராமப்புற சுகாதார உதவியாளர்',
    greeting: 'வணக்கம்',
    pillbox_title: '5-நாள் காட்சி மாத்திரை பெட்டி',
    morning: 'காலை',
    afternoon: 'மதியம்',
    evening: 'மாலை',
    night: 'இரவு',
    before_food: 'உணவுக்கு முன்',
    after_food: 'உணவுக்கு பின்',
    with_food: 'உணவுடன்',
    mark_taken: 'மருந்து எடு',
    dose_taken: 'மருந்து எடுக்கப்பட்டது ✅',
    streak: 'நாட்கள் தொடர்ச்சி',
    scan_prescription: 'மருந்துச் சீட்டை ஸ்கேன் செய்',
    health_card: 'ABHA சுகாதார அட்டை',
    emergency_sos: 'அவசர உதவி (SOS)',
    listen_voice: 'குரலில் கேளுங்கள்',
    view_all_prescriptions: 'எனது மருந்துகள்',
    asha_roster: 'நோயாளி பட்டியல்',
    sync_status: 'இணைப்பு: ஆன்லைன்',
    sync_offline: 'ஆஃப்லைன் பயன்முறை',
    caregiver_monitoring: 'குடும்ப கண்காணிப்பு',
  },
  te: {
    app_title: 'స్వాస్థ్య AI',
    app_subtitle: 'గ్రామీణ ఆరోగ్య సహాయకుడు',
    greeting: 'నమస్కారం',
    pillbox_title: '5-రోజుల విజువల్ పిల్ బాక్స్',
    morning: 'ఉదయం',
    afternoon: 'మధ్యాహ్నం',
    evening: 'సాయంత్రం',
    night: 'రాత్రి',
    before_food: 'భోజనానికి ముందు',
    after_food: 'భోజనం తర్వాత',
    with_food: 'భోజనంతో పాటు',
    mark_taken: 'మందు తీసుకోండి',
    dose_taken: 'మందు తీసుకున్నారు ✅',
    streak: 'రోజుల నియమం',
    scan_prescription: 'ప్రిస్క్రిప్షన్ స్కాన్ చేయండి',
    health_card: 'ABHA హెల్త్ కార్డ్',
    emergency_sos: 'అత్యవసర సహాయం (SOS)',
    listen_voice: 'వాయిస్‌లో వినండి',
    view_all_prescriptions: 'నా ప్రిస్క్రిప్షన్లు',
    asha_roster: 'రోగుల జాబితా',
    sync_status: 'ఆన్‌లైన్',
    sync_offline: 'ఆఫ్‌లైన్ మోడ్',
    caregiver_monitoring: 'కుటుంబ పర్యవేక్షణ',
  },
  bn: {
    app_title: 'স্বাস্থ্যা এআই',
    app_subtitle: 'গ্রামীণ স্বাস্থ্যসেবা যোগাযোগ সহায়ক',
    greeting: 'নমস্কার',
    pillbox_title: '৫-দিনের ভিজ্যুয়াল পিলবক্স',
    morning: 'সকাল',
    afternoon: 'দুপুর',
    evening: 'সন্ধ্যা',
    night: 'রাত',
    before_food: 'খাওয়ার আগে',
    after_food: 'খাওয়ার পরে',
    with_food: 'খাবারের সাথে',
    mark_taken: 'ওষুধ খান',
    dose_taken: 'ওষুধ নেওয়া হয়েছে ✅',
    streak: 'দিনের ধারাবাহিকতা',
    scan_prescription: 'প্রেসক্রিপশন স্ক্যান করুন',
    health_card: 'আভা স্বাস্থ্য কার্ড',
    emergency_sos: 'জরুরি এসওএস (SOS)',
    listen_voice: 'কণ্ঠে শুনুন',
    view_all_prescriptions: 'আমার প্রেসক্রিপশন',
    asha_roster: 'রোগীদের তালিকা',
    sync_status: 'অনলাইন',
    sync_offline: 'অফলাইন মোড',
    caregiver_monitoring: 'পারিবারিক পর্যবেক্ষণ',
  },
};
