# Generated by Django 5.2.16 on 2026-07-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('medical_report', 'Medical Report'), ('health_content', 'Health Content')], default='prescription', max_length=32)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='medical_documents/')),
                ('text_content', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('or', 'Oriya')], default='en', max_length=8)),
                ('translated_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
