# Generated by Django 5.2.16 on 2026-07-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_medicaldocument_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'ordering': ['-created_at']},
        ),
    ]
