# Generated by Django 5.2.11 on 2026-08-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_alter_medicaldocument_options'),
        ('patients', '0003_patientcaregiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('PHC', 'Primary Health Centre'), ('CHC', 'Community Health Centre'), ('HOSPITAL', 'Hospital / District Hospital'), ('CLINIC', 'Clinic'), ('PHARMACY', 'Pharmacy / Jan Aushadhi Kendra'), ('BLOOD_BANK', 'Blood Bank / Storage Unit'), ('AMBULANCE_BASE', 'Ambulance Station')], default='PHC', max_length=64)),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('services_list', models.JSONField(blank=True, default=list)),
                ('data_provenance', models.CharField(default='VERIFIED_STATIC', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('emergency_type', models.CharField(default='General Medical Emergency', max_length=64)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('address_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_sessions', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_meters', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='medical.emergencysession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
