# Generated by Django 5.2.16 on 2026-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_emergencysession_heading_emergencysession_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='abnormal_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Prescription (OPD Rx)'), ('discharge_summary', 'Hospital Discharge Summary'), ('diagnostic_report', 'Diagnostic & Lab Report'), ('radiology_scan', 'Radiology & Scans (X-Ray/USG)'), ('immunization', 'Vaccine & Immunization'), ('medical_report', 'Other Medical Report'), ('health_content', 'Health Content')], default='prescription', max_length=32),
        ),
    ]
