# Generated by Django 5.2.16 on 2026-07-27 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('health_worker', 'Health Worker'), ('other', 'Other')], default='health_worker', max_length=32)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('qualifications', models.CharField(blank=True, max_length=512)),
                ('registration_number', models.CharField(blank=True, max_length=128)),
                ('specialties', models.CharField(blank=True, help_text='Comma-separated specialties', max_length=512)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
