# Generated by Django 5.2.11 on 2026-07-27 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0002_alter_medicaldocument_patient'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('form', models.CharField(blank=True, max_length=128)),
                ('strength', models.CharField(blank=True, max_length=128)),
                ('dosage_text', models.CharField(blank=True, max_length=512)),
                ('dosage_amount', models.CharField(blank=True, max_length=64)),
                ('dosage_unit', models.CharField(blank=True, max_length=32)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('thrice_daily', 'Thrice Daily'), ('as_needed', 'As needed'), ('other', 'Other')], default='other', max_length=32)),
                ('before_food', models.BooleanField(default=False)),
                ('after_food', models.BooleanField(default=False)),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('night', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('extracted', 'Extracted'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medications', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications', to='medical.medicaldocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
