# Generated by Django 5.2.16 on 2026-09-01 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientcaregiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='abha_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.CreateModel(
            name='PatientClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(default='healthcare_worker', max_length=32)),
                ('note_type', models.CharField(default='field_visit', max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('audio_url', models.TextField(blank=True)),
                ('language', models.CharField(default='hi', max_length=16)),
                ('blood_pressure', models.CharField(blank=True, max_length=32)),
                ('blood_sugar', models.CharField(blank=True, max_length=32)),
                ('pulse', models.CharField(blank=True, max_length=32)),
                ('temperature', models.CharField(blank=True, max_length=32)),
                ('weight', models.CharField(blank=True, max_length=32)),
                ('symptoms', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_clinical_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
