# Generated by Django 5.2.16 on 2026-07-31 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('healthcare_worker', 'Healthcare Worker'), ('caregiver', 'Caregiver'), ('admin', 'Admin')], default='patient', max_length=32),
        ),
    ]
