# Generated by Django 5.2.16 on 2026-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='abha_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='abha_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('healthcare_worker', 'Healthcare Worker'), ('doctor', 'Doctor'), ('caregiver', 'Caregiver'), ('admin', 'Admin')], default='patient', max_length=32),
        ),
    ]
