# Generated by Django 5.0.14 on 2026-08-06 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_healthcareworkerprofile_healthcontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('prescription', 'Prescription'), ('discharge_summary', 'Discharge Summary'), ('instruction', 'Healthcare Instruction'), ('other', 'Other')], default='other', max_length=20)),
                ('source_text', models.TextField(help_text='Original extracted or provided text')),
                ('target_language', models.CharField(help_text='e.g. hi, ta, te, bn, mr, gu, kn', max_length=10)),
                ('translated_text', models.TextField(blank=True)),
                ('simplified_explanation', models.TextField(blank=True, help_text='Plain-language explanation of medical terms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='accounts.medicaldocument')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
