# Generated by Django 5.0.14 on 2026-08-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_medicalentityextraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='The symptom or health question asked')),
                ('language', models.CharField(default='en', max_length=10)),
                ('symptom_information', models.TextField(blank=True)),
                ('possible_related_conditions', models.JSONField(blank=True, default=list)),
                ('disease_awareness', models.TextField(blank=True)),
                ('preventive_care', models.JSONField(blank=True, default=list)),
                ('when_to_see_a_doctor', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
